### PR TITLE
fix(receiver): Properly ignore non-data messages

### PR DESCRIPTION
**Pull request by kalbasit**
### TL;DR
Added a new `IsDataMessage()` helper method to improve message type validation.

### What changed?
- Added `IsDataMessage()` method to the `Message` struct to check if a message is a data message
- Updated `recordMessage()` to use the new helper method instead of direct nil checks
- The new method ensures a message is a data message by verifying it has DataMessage content while excluding receipt, typing, and sync messages

### How to test?
1. Send different types of messages (regular messages, typing indicators, receipts, sync messages)
2. Verify that only actual data messages are being recorded
3. Confirm that typing indicators, receipts, and sync messages are properly logged but not recorded

### Why make this change?
The previous implementation only checked for nil DataMessage and Message fields, which wasn't comprehensive enough to filter out all non-data message types. This change provides a more robust way to identify data messages while making the code more maintainable and easier to understand.

### CODE REVIEW

**Comment by kalbasit** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/kalbasit/signal-api-receiver/29?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#29** <a href="https://app.graphite.dev/github/pr/kalbasit/signal-api-receiver/29?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/kalbasit/signal-api-receiver/29?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#28** <a href="https://app.graphite.dev/github/pr/kalbasit/signal-api-receiver/28?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by kalbasit** [comment]
@mafredri  In #8 (merged in #21) you added a skip for non-data messages, however, it was too restrictive and it was removing messages that are only attachments or stickers; Was that intentional? This PR removes this restriction and explicitly only ignores typing/receipt and sync messages.

**Comment by kalbasit** [comment]
I ended up implementing a flag that controls which messages should be ignored, and by default it ignores messages with empty data and empty data.message (current behavior) so I'm going to go ahead and close this PR.

**Comment by mafredri** [comment]
@kalbasit good catch on the restrictiveness of checking `DataMessage.Message != nil`. I added it to handle group invites/updates, as those were being delivered with data message set but `message = null`. The new condition won't filter out these.

Here are two examples:

```
[
	{
		"envelope": {
			"source": "************",
			"sourceNumber": "************",
			"sourceUuid": "4ebfc054-558a-4705-b331-a85c5c4f3ab9",
			"sourceName": "*******",
			"sourceDevice": 2,
			"timestamp": 0,
			"dataMessage": {
				"timestamp": 0,
				"message": null,
				"expiresInSeconds": 0,
				"viewOnce": false,
				"groupInfo": {
					"groupId": "[group_id],
					"type": "DELIVER"
				}
			}
		},
		"account": "************"
	},
	{
		"envelope": {
			"source": "************",
			"sourceNumber": "************",
			"sourceUuid": "4ebfc054-558a-4705-b331-a85c5c4f3ab9",
			"sourceName": "*******",
			"sourceDevice": 2,
			"timestamp": 0,
			"dataMessage": {
				"timestamp": 0,
				"message": null,
				"expiresInSeconds": 0,
				"viewOnce": false,
				"groupInfo": {
					"groupId": "[group_id],
					"type": "UPDATE"
				}
			}
		},
		"account": "************"
	}
]
```

**Pull request closed without merging**
